//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Search_MVC_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Login
    {
        public int Log_Id { get; set; }
        public int Register_Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Log_Type { get; set; }
        public string Status { get; set; }
    }
}
