//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Search_MVC_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_User
    {
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public int User_Age { get; set; }
        public string User_Address { get; set; }
        public long User_Phone { get; set; }
        public string User_Email { get; set; }
        public long User_Pincode { get; set; }
        public string User_State { get; set; }
        public string User_District { get; set; }
        public string User_Qualification { get; set; }
        public string User_Skills { get; set; }
        public string User_Experience { get; set; }
        public string User_Status { get; set; }
    }
}
