//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Search_MVC_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Company
    {
        public int Company_Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Address { get; set; }
        public long Company_Phone { get; set; }
        public string Company_Email { get; set; }
        public string Company_Status { get; set; }
    }
}
